config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'api' => 'home#api', as: 'api'
  
  require 'dispatch'
  mount GrapeSwaggerRails::Engine => '/apidoc'
  mount API::Dispatch => '/api'
  
  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => 'sidekiq'
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    redirect_to admin_root_url
  end
  
  def api
    @routes = []
    API::Dispatch.routes.each do |route|
      next if route.route_method.blank?
      path = route.route_path
      path.sub!('(.:format)', '.json')
      path.sub!('/:version', '')
      
      r = {
        id: path.dasherize,
        method: route.route_method,
        name: path,
        params: route.route_params,
        desc: route.route_description
      }
      @routes << r
    end
    @routes.sort_by! { |a| a[:name] }
  end
  
end

app/views/home/api.html.erb
<% cache(["api", "v1.0"], expires_in: 1.days) do %>
<div class="panel panel-default api-doc">
  <div class="panel-heading">Lease Goods API Doc</div>
  <div class="panel-body markdown">
    <h4>OAuth 2 / API 认证</h4>
    <p>
      在使用 API 之前，你需要 <%= link_to "注册应用", new_oauth_application_path, target: "_blank" %> 并获得可以 OAuth App 信息。并使用标准的 OAuth 2 实现登录，获得 <code>access_token</code> 信息。
    </p>
    <h5>OAuth 路径</h5>
    <ul>
      <li>https://<%= Setting.domain %>/oauth/authorize</li>
      <li>https://<%= Setting.domain %>/oauth/token</li>
      <li>https://<%= Setting.domain %>/oauth/revoke</li>
    </ul>
    <h4>Response 说明</h4>
    <p>所有 Response 采用 JSON 格式返回，请求状态通过 HTTP Status 返回</p>
    <h5>HTTP Status</h5>
    <ul>
      <li>200, 201 - 请求成功，或执行成功</li>
      <li>400 - 参数不符合 API 的要求、或者数据格式验证没有通过，请配合 Response Body 里面的 error 信息确定问题。</li>
      <li>401 - 用户认证失败，或缺少认证信息，比如 access_token 过期，或没传，可以尝试用 refresh_token 方式获得新的 access_token。</li>
      <li>403 - 当前用户对资源没有操作权限</li>
      <li>404 - 资源不存在。</li>
      <li>500 - 服务器异常</li>
    </ul>
    <p>错误的情况 Response Body 一定会是这样的格式: <code>{ "error" : "Error message" }</code></p>
    <h5>资源权限描述</h5>
    <p>在部分 API 的 response 内容里面你会看到 <code>abilities</code> 节点，这是特别标识当前 access_token 对应的用户对此资源的权限</p>
    <p>请参考源代码，确定那些路径是需要用户认证的，需要用户认证的路径，你需要带上 <code>access_token=?</code> 参数。</p>
    <strong>例如</strong>
    <ul>
      <li><code>update</code> - 是否有权限修改</li>
      <li><code>destroy</code> - 是否有权限删除</li>
    </ul>
    <h4>API 路由</h4>
    <p>下面是简单的 API 路由列表, 具体请参考源代码 <a href="https://github.com/ruby-china/ruby-china/blob/master/app/api" target="_blank">app/api</a></p>
    <p>URL 基本路径：<%= request.protocol %><%= Setting.domain %>/api/v3</p>
    <div class="row">
      <div class="col-md-3">
        <ul class="route-list">
          <% @routes.each do |route| %>
          <li><%= route[:method] %> <a href="#route-<%= route[:id] %>"><%= route[:name] %></a></li>
          <% end %>
        </ul>
      </div>
      <div class="routes col-md-9">
        <% @routes.each do |route| %>
        <div class="route" id="route-<%= route[:id] %>">
          <h5><label><%= route[:method] %></label> <%= route[:name] %></h5>
          <div class="content">
            <div class="desc markdown"><%= markdown(route[:desc] || "暂无") %></div>
            <% if route[:params].count > 0 %>
            <h6>Params</h6>
            <table class="table table-striped table-bordered params">
              <thead>
                <th>参数名</th>
                <th>类型</th>
                <th>必填</th>
                <th>默认值</th>
                <th>值范围</th>
                <th>说明</th>
              </thead>
              <tbody>
                <% route[:params].each do |k,param| %>
                <%
                if not param.is_a?(Hash)
                  param = { type: "String", required: true, desc: "主键" }
                end
                %>
                <tr>
                  <td class="field"><%= k %></td>
                  <td class="type"><%= param[:type] %></td>
                  <td class="required"><%= param[:required] %></td>
                  <td class="default"><%= param[:default] %></td>
                  <td class="values"><%= param[:values] %></td>
                  <td><%= markdown(param[:desc] || "") %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <h4>Example</h4>
    <div style="margin-bottom:10px;">
      <p>我们用 Ruby 演示一下访问 /api/v3/hello.json 这个路径，其中包含 OAuth 2 的流程。</p>
      <p>这里用到 RubyGem <a href="https://github.com/intridea/oauth2" target="_blank">oauth2</a>
    </div>
  </div>
</div>
<% end %>

app/views/home/index.html.erb
<%= link_to 'Admin', admin_root_path %>